'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('daybook', {
  bootstrap: () => ipcRenderer.invoke('bootstrap'),
  join: (payload) => ipcRenderer.invoke('join', payload),
  welcomeMessage: () => ipcRenderer.invoke('welcome-message'),
  introStart: () => ipcRenderer.invoke('intro-start'),
  introNext: (payload) => ipcRenderer.invoke('intro-next', payload),
  introWrite: (payload) => ipcRenderer.invoke('intro-write', payload),
  onGenStream: (cb) => { const h = (_e, d) => cb(d); ipcRenderer.on('gen-stream', h); return () => ipcRenderer.removeListener('gen-stream', h); },
  transcribeAudio: (payload) => ipcRenderer.invoke('transcribe-audio', payload),
  warmWhisper: () => ipcRenderer.invoke('warm-whisper'),
  markIntroduced: () => ipcRenderer.invoke('mark-introduced'),
  collect: () => ipcRenderer.invoke('collect'),
  generate: (payload) => ipcRenderer.invoke('generate', payload),
  post: (content) => ipcRenderer.invoke('post', content),
  revise: (payload) => ipcRenderer.invoke('revise', payload),
  getLearned: () => ipcRenderer.invoke('get-learned'),
  clearLearned: () => ipcRenderer.invoke('clear-learned'),
  openFeed: (server) => ipcRenderer.invoke('open-feed', server),
  linkHostStart: (perms) => ipcRenderer.invoke('link-host-start', { perms }),
  linkHostStop: () => ipcRenderer.invoke('link-host-stop'),
  linkHostInfo: () => ipcRenderer.invoke('link-host-info'),
  linkConnect: (code) => ipcRenderer.invoke('link-connect', { code }),
  linkDisconnect: () => ipcRenderer.invoke('link-disconnect'),
  linkStatus: () => ipcRenderer.invoke('link-status'),
  linkPeerRecent: (days) => ipcRenderer.invoke('link-peer-recent', { days }),
  linkPeerRaw: (days) => ipcRenderer.invoke('link-peer-raw', { days }),
  linkSshConnect: (target) => ipcRenderer.invoke('link-ssh-connect', { target }),
  linkSshDisconnect: () => ipcRenderer.invoke('link-ssh-disconnect'),
  linkSshRecent: (days) => ipcRenderer.invoke('link-ssh-recent', { days }),
  linkSshRaw: (days) => ipcRenderer.invoke('link-ssh-raw', { days }),
  linkPeersList: () => ipcRenderer.invoke('link-peers-list'),
  linkPeerRemove: (target) => ipcRenderer.invoke('link-peer-remove', { target }),
  onLinkHostChanged: (cb) => { const h = (_e, i) => cb(i); ipcRenderer.on('link-host-changed', h); return () => ipcRenderer.removeListener('link-host-changed', h); },
  // ── Scope + redaction (Invariants I1–I5) ────────────────────────────────
  scopeGet: () => ipcRenderer.invoke('scope:get'),
  scopeSetRule: (payload) => ipcRenderer.invoke('scope:setRule', payload),
  scopeOverride: (payload) => ipcRenderer.invoke('scope:override', payload),
  scopeSetConversation: (payload) => ipcRenderer.invoke('scope:setConversation', payload),
  scopePreview: (payload) => ipcRenderer.invoke('scope:preview', payload),
  redactionRule: (payload) => ipcRenderer.invoke('redaction:rule', payload),
  redactionReveal: (payload) => ipcRenderer.invoke('redaction:reveal', payload),
});
